import { SetMetadata } from '@nestjs/common';

// eslint-disable-next-line no-shadow
export enum ThrowErrorEnum {
  FLEET_NOT_FOUND = 'FLEET_NOT_FOUND',
  ERROR = 'ERROR',
  DUPLICATE_KEY = 'DUPLICATE_KEY',
  DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  AUTHORIZATION_NOT_FOUND = 'AUTHORIZATION_NOT_FOUND',
  TRANSPORT_COMPANY_NOT_FOUND = 'TRANSPORT_COMPANY_NOT_FOUND',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  PHONE_NUMBER_ALREADY_USED = 'PHONE_NUMBER_ALREADY_USED',
  EMAIL_OR_PASSWORD_NOT_CORRECT = 'EMAIL_OR_PASSWORD_NOT_CORRECT',
  TRIP_REQUEST_NOT_FOUND = 'TRIP_REQUEST_NOT_FOUND',
  TRIP_REQUEST_HAD_CONFIRMED = 'TRIP_REQUEST_HAD_CONFIRMED',
  VEHICLE_NOT_FOUND = 'VEHICLE_NOT_FOUND',
  INAPPROPRIATE_STATUS = 'INAPPROPRIATE_STATUS',
  ONLY_END_USER_CANCEL_ONGOING_TRIP_REUQEST = 'ONLY_END_USER_CANCEL_ONGOING_TRIP_REUQEST',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FORMAT_FILES_ARE_ALLOWED = 'FORMAT_FILES_ARE_ALLOWED',
  PASSWORD_TO_WEAK = 'PASSWORD_TO_WEAK',
  EMAIL_INVALIDATED = 'EMAIL_INVALIDATED',
  OPT_NOT_MATCH = 'OPT_NOT_MATCH',
  PASSWORD_NOT_CORRECT = 'PASSWORD_NOT_CORRECT',
}

export const error = (...error: ThrowErrorEnum[]) =>
  SetMetadata('error', error);
